name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  AZURE_CONTAINER_REGISTRY: piqlenwvfzysqcosureg.azurecr.io
  AZURE_APP_SERVICE_NAME: piqlenwvfzysq-app
  AZURE_RESOURCE_GROUP: techworkshop-l300-ai-agents-au
  IMAGE_NAME: chat-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: $

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: $
          username: $
          password: $

      - name: Build and push Docker image
        run: |
          cd src/
          docker build -t piqlenwvfzysqcosureg.azurecr.io/chat-app:latest .
          docker push piqlenwvfzysqcosureg.azurecr.io/chat-app:latest
